/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReservationId = IDL.Nat;
export const ProductId = IDL.Nat;
export const RentalId = IDL.Nat;
export const VerhuurStatus = IDL.Variant({
  'Actief' : IDL.Null,
  'Ingeleverd' : IDL.Null,
  'TeLaat' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Verhuur = IDL.Record({
  'id' : RentalId,
  'status' : VerhuurStatus,
  'klantNaam' : IDL.Text,
  'klantContact' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'isSet' : IDL.Bool,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
});
export const ProductType = IDL.Variant({
  'Boots' : IDL.Null,
  'Snowboard' : IDL.Null,
  'Bindingen' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'maat' : IDL.Text,
  'naam' : IDL.Text,
  'prijsPerDag' : IDL.Nat,
  'productType' : ProductType,
  'beschikbaar' : IDL.Bool,
  'qrCode' : IDL.Text,
});
export const ReserveringStatus = IDL.Variant({
  'Bevestigd' : IDL.Null,
  'InAfwachting' : IDL.Null,
  'Geannuleerd' : IDL.Null,
});
export const Reservering = IDL.Record({
  'id' : ReservationId,
  'status' : ReserveringStatus,
  'contactNaam' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'contactTelefoon' : IDL.Text,
  'aangemaakt' : Timestamp,
  'contactEmail' : IDL.Text,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
});
export const UserRole = IDL.Variant({
  'Admin' : IDL.Null,
  'Medewerker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'contactInfo' : IDL.Text,
  'naam' : IDL.Text,
  'role' : UserRole,
});
export const ProductFilter = IDL.Record({
  'maat' : IDL.Opt(IDL.Text),
  'productType' : IDL.Opt(ProductType),
  'beschikbaar' : IDL.Opt(IDL.Bool),
});
export const NieuweReservering = IDL.Record({
  'contactNaam' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'contactTelefoon' : IDL.Text,
  'contactEmail' : IDL.Text,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
});
export const NieuweVerhuur = IDL.Record({
  'klantNaam' : IDL.Text,
  'klantContact' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'isSet' : IDL.Bool,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
});

export const idlService = IDL.Service({
  'annuleerReservering' : IDL.Func([ReservationId], [IDL.Bool], []),
  'bevestigReservering' : IDL.Func([ReservationId], [IDL.Bool], []),
  'bewerkProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'getActieveVerhuringen' : IDL.Func([], [IDL.Vec(Verhuur)], ['query']),
  'getAlleProductenVoorQrBatch' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAlleReserveringen' : IDL.Func([], [IDL.Vec(Reservering)], ['query']),
  'getBeschikbareProducten' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getMijnProfiel' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMijnRol' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducten' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getVerhuur' : IDL.Func([RentalId], [IDL.Opt(Verhuur)], ['query']),
  'getVervallenVerhuringen' : IDL.Func([], [IDL.Vec(Verhuur)], ['query']),
  'markeerIngeleverd' : IDL.Func([RentalId], [IDL.Bool], []),
  'plaatsReserveringPubliek' : IDL.Func(
      [NieuweReservering],
      [ReservationId],
      [],
    ),
  'registreerMedewerker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'startVerhuur' : IDL.Func([NieuweVerhuur], [RentalId], []),
  'verwijderProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'voegProductToe' : IDL.Func(
      [IDL.Text, ProductType, IDL.Text, IDL.Nat],
      [ProductId],
      [],
    ),
  'zoekProductOpQrCode' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReservationId = IDL.Nat;
  const ProductId = IDL.Nat;
  const RentalId = IDL.Nat;
  const VerhuurStatus = IDL.Variant({
    'Actief' : IDL.Null,
    'Ingeleverd' : IDL.Null,
    'TeLaat' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Verhuur = IDL.Record({
    'id' : RentalId,
    'status' : VerhuurStatus,
    'klantNaam' : IDL.Text,
    'klantContact' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'isSet' : IDL.Bool,
    'eindDatum' : Timestamp,
    'startDatum' : Timestamp,
  });
  const ProductType = IDL.Variant({
    'Boots' : IDL.Null,
    'Snowboard' : IDL.Null,
    'Bindingen' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'maat' : IDL.Text,
    'naam' : IDL.Text,
    'prijsPerDag' : IDL.Nat,
    'productType' : ProductType,
    'beschikbaar' : IDL.Bool,
    'qrCode' : IDL.Text,
  });
  const ReserveringStatus = IDL.Variant({
    'Bevestigd' : IDL.Null,
    'InAfwachting' : IDL.Null,
    'Geannuleerd' : IDL.Null,
  });
  const Reservering = IDL.Record({
    'id' : ReservationId,
    'status' : ReserveringStatus,
    'contactNaam' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'contactTelefoon' : IDL.Text,
    'aangemaakt' : Timestamp,
    'contactEmail' : IDL.Text,
    'eindDatum' : Timestamp,
    'startDatum' : Timestamp,
  });
  const UserRole = IDL.Variant({ 'Admin' : IDL.Null, 'Medewerker' : IDL.Null });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'contactInfo' : IDL.Text,
    'naam' : IDL.Text,
    'role' : UserRole,
  });
  const ProductFilter = IDL.Record({
    'maat' : IDL.Opt(IDL.Text),
    'productType' : IDL.Opt(ProductType),
    'beschikbaar' : IDL.Opt(IDL.Bool),
  });
  const NieuweReservering = IDL.Record({
    'contactNaam' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'contactTelefoon' : IDL.Text,
    'contactEmail' : IDL.Text,
    'eindDatum' : Timestamp,
    'startDatum' : Timestamp,
  });
  const NieuweVerhuur = IDL.Record({
    'klantNaam' : IDL.Text,
    'klantContact' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'isSet' : IDL.Bool,
    'eindDatum' : Timestamp,
    'startDatum' : Timestamp,
  });
  
  return IDL.Service({
    'annuleerReservering' : IDL.Func([ReservationId], [IDL.Bool], []),
    'bevestigReservering' : IDL.Func([ReservationId], [IDL.Bool], []),
    'bewerkProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'getActieveVerhuringen' : IDL.Func([], [IDL.Vec(Verhuur)], ['query']),
    'getAlleProductenVoorQrBatch' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAlleReserveringen' : IDL.Func([], [IDL.Vec(Reservering)], ['query']),
    'getBeschikbareProducten' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getMijnProfiel' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMijnRol' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducten' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getVerhuur' : IDL.Func([RentalId], [IDL.Opt(Verhuur)], ['query']),
    'getVervallenVerhuringen' : IDL.Func([], [IDL.Vec(Verhuur)], ['query']),
    'markeerIngeleverd' : IDL.Func([RentalId], [IDL.Bool], []),
    'plaatsReserveringPubliek' : IDL.Func(
        [NieuweReservering],
        [ReservationId],
        [],
      ),
    'registreerMedewerker' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'startVerhuur' : IDL.Func([NieuweVerhuur], [RentalId], []),
    'verwijderProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'voegProductToe' : IDL.Func(
        [IDL.Text, ProductType, IDL.Text, IDL.Nat],
        [ProductId],
        [],
      ),
    'zoekProductOpQrCode' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };