/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NieuweReservering {
  'contactNaam' : string,
  'productIds' : Array<ProductId>,
  'contactTelefoon' : string,
  'contactEmail' : string,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
}
export interface NieuweVerhuur {
  'klantNaam' : string,
  'klantContact' : string,
  'productIds' : Array<ProductId>,
  'isSet' : boolean,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
}
export interface Product {
  'id' : ProductId,
  'maat' : string,
  'naam' : string,
  'prijsPerDag' : bigint,
  'productType' : ProductType,
  'beschikbaar' : boolean,
  'qrCode' : string,
}
export interface ProductFilter {
  'maat' : [] | [string],
  'productType' : [] | [ProductType],
  'beschikbaar' : [] | [boolean],
}
export type ProductId = bigint;
export type ProductType = { 'Boots' : null } |
  { 'Snowboard' : null } |
  { 'Bindingen' : null };
export type RentalId = bigint;
export type ReservationId = bigint;
export interface Reservering {
  'id' : ReservationId,
  'status' : ReserveringStatus,
  'contactNaam' : string,
  'productIds' : Array<ProductId>,
  'contactTelefoon' : string,
  'aangemaakt' : Timestamp,
  'contactEmail' : string,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
}
export type ReserveringStatus = { 'Bevestigd' : null } |
  { 'InAfwachting' : null } |
  { 'Geannuleerd' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'principal' : Principal,
  'contactInfo' : string,
  'naam' : string,
  'role' : UserRole,
}
export type UserRole = { 'Admin' : null } |
  { 'Medewerker' : null };
export interface Verhuur {
  'id' : RentalId,
  'status' : VerhuurStatus,
  'klantNaam' : string,
  'klantContact' : string,
  'productIds' : Array<ProductId>,
  'isSet' : boolean,
  'eindDatum' : Timestamp,
  'startDatum' : Timestamp,
}
export type VerhuurStatus = { 'Actief' : null } |
  { 'Ingeleverd' : null } |
  { 'TeLaat' : null };
export interface _SERVICE {
  'annuleerReservering' : ActorMethod<[ReservationId], boolean>,
  'bevestigReservering' : ActorMethod<[ReservationId], boolean>,
  'bewerkProduct' : ActorMethod<
    [ProductId, string, string, bigint, boolean],
    boolean
  >,
  'getActieveVerhuringen' : ActorMethod<[], Array<Verhuur>>,
  'getAlleProductenVoorQrBatch' : ActorMethod<[], Array<Product>>,
  'getAlleReserveringen' : ActorMethod<[], Array<Reservering>>,
  'getBeschikbareProducten' : ActorMethod<
    [Timestamp, Timestamp],
    Array<Product>
  >,
  'getMijnProfiel' : ActorMethod<[], [] | [UserProfile]>,
  'getMijnRol' : ActorMethod<[], [] | [UserRole]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducten' : ActorMethod<[ProductFilter], Array<Product>>,
  'getVerhuur' : ActorMethod<[RentalId], [] | [Verhuur]>,
  'getVervallenVerhuringen' : ActorMethod<[], Array<Verhuur>>,
  'markeerIngeleverd' : ActorMethod<[RentalId], boolean>,
  'plaatsReserveringPubliek' : ActorMethod<[NieuweReservering], ReservationId>,
  'registreerMedewerker' : ActorMethod<[string, string], boolean>,
  'startVerhuur' : ActorMethod<[NieuweVerhuur], RentalId>,
  'verwijderProduct' : ActorMethod<[ProductId], boolean>,
  'voegProductToe' : ActorMethod<
    [string, ProductType, string, bigint],
    ProductId
  >,
  'zoekProductOpQrCode' : ActorMethod<[string], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];