/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Verhuur {
    id: RentalId;
    status: VerhuurStatus;
    klantNaam: string;
    klantContact: string;
    productIds: Array<ProductId>;
    isSet: boolean;
    eindDatum: Timestamp;
    startDatum: Timestamp;
}
export type Timestamp = bigint;
export interface Reservering {
    id: ReservationId;
    status: ReserveringStatus;
    contactNaam: string;
    productIds: Array<ProductId>;
    contactTelefoon: string;
    aangemaakt: Timestamp;
    contactEmail: string;
    eindDatum: Timestamp;
    startDatum: Timestamp;
}
export type ReservationId = bigint;
export interface NieuweVerhuur {
    klantNaam: string;
    klantContact: string;
    productIds: Array<ProductId>;
    isSet: boolean;
    eindDatum: Timestamp;
    startDatum: Timestamp;
}
export interface ProductFilter {
    maat?: string;
    productType?: ProductType;
    beschikbaar?: boolean;
}
export type RentalId = bigint;
export interface NieuweReservering {
    contactNaam: string;
    productIds: Array<ProductId>;
    contactTelefoon: string;
    contactEmail: string;
    eindDatum: Timestamp;
    startDatum: Timestamp;
}
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    maat: string;
    naam: string;
    prijsPerDag: bigint;
    productType: ProductType;
    beschikbaar: boolean;
    qrCode: string;
}
export interface UserProfile {
    principal: Principal;
    contactInfo: string;
    naam: string;
    role: UserRole;
}
export enum ProductType {
    Boots = "Boots",
    Snowboard = "Snowboard",
    Bindingen = "Bindingen"
}
export enum ReserveringStatus {
    Bevestigd = "Bevestigd",
    InAfwachting = "InAfwachting",
    Geannuleerd = "Geannuleerd"
}
export enum UserRole {
    Admin = "Admin",
    Medewerker = "Medewerker"
}
export enum VerhuurStatus {
    Actief = "Actief",
    Ingeleverd = "Ingeleverd",
    TeLaat = "TeLaat"
}
export interface backendInterface {
    annuleerReservering(id: ReservationId): Promise<boolean>;
    bevestigReservering(id: ReservationId): Promise<boolean>;
    bewerkProduct(id: ProductId, naam: string, maat: string, prijsPerDag: bigint, beschikbaar: boolean): Promise<boolean>;
    getActieveVerhuringen(): Promise<Array<Verhuur>>;
    getAlleProductenVoorQrBatch(): Promise<Array<Product>>;
    getAlleReserveringen(): Promise<Array<Reservering>>;
    getBeschikbareProducten(startDatum: Timestamp, eindDatum: Timestamp): Promise<Array<Product>>;
    getMijnProfiel(): Promise<UserProfile | null>;
    getMijnRol(): Promise<UserRole | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProducten(filter: ProductFilter): Promise<Array<Product>>;
    getVerhuur(id: RentalId): Promise<Verhuur | null>;
    getVervallenVerhuringen(): Promise<Array<Verhuur>>;
    markeerIngeleverd(id: RentalId): Promise<boolean>;
    plaatsReserveringPubliek(invoer: NieuweReservering): Promise<ReservationId>;
    registreerMedewerker(naam: string, contactInfo: string): Promise<boolean>;
    startVerhuur(invoer: NieuweVerhuur): Promise<RentalId>;
    verwijderProduct(id: ProductId): Promise<boolean>;
    voegProductToe(naam: string, productType: ProductType, maat: string, prijsPerDag: bigint): Promise<ProductId>;
    zoekProductOpQrCode(qrCode: string): Promise<Product | null>;
}
import type { Product as _Product, ProductFilter as _ProductFilter, ProductId as _ProductId, ProductType as _ProductType, RentalId as _RentalId, ReservationId as _ReservationId, Reservering as _Reservering, ReserveringStatus as _ReserveringStatus, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, Verhuur as _Verhuur, VerhuurStatus as _VerhuurStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async annuleerReservering(arg0: ReservationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.annuleerReservering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.annuleerReservering(arg0);
            return result;
        }
    }
    async bevestigReservering(arg0: ReservationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bevestigReservering(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bevestigReservering(arg0);
            return result;
        }
    }
    async bewerkProduct(arg0: ProductId, arg1: string, arg2: string, arg3: bigint, arg4: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bewerkProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bewerkProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getActieveVerhuringen(): Promise<Array<Verhuur>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActieveVerhuringen();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActieveVerhuringen();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlleProductenVoorQrBatch(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlleProductenVoorQrBatch();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlleProductenVoorQrBatch();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlleReserveringen(): Promise<Array<Reservering>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlleReserveringen();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlleReserveringen();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBeschikbareProducten(arg0: Timestamp, arg1: Timestamp): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBeschikbareProducten(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBeschikbareProducten(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMijnProfiel(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMijnProfiel();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMijnProfiel();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMijnRol(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMijnRol();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMijnRol();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducten(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducten(to_candid_ProductFilter_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducten(to_candid_ProductFilter_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerhuur(arg0: RentalId): Promise<Verhuur | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerhuur(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerhuur(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVervallenVerhuringen(): Promise<Array<Verhuur>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVervallenVerhuringen();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVervallenVerhuringen();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async markeerIngeleverd(arg0: RentalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markeerIngeleverd(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markeerIngeleverd(arg0);
            return result;
        }
    }
    async plaatsReserveringPubliek(arg0: NieuweReservering): Promise<ReservationId> {
        if (this.processError) {
            try {
                const result = await this.actor.plaatsReserveringPubliek(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.plaatsReserveringPubliek(arg0);
            return result;
        }
    }
    async registreerMedewerker(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registreerMedewerker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registreerMedewerker(arg0, arg1);
            return result;
        }
    }
    async startVerhuur(arg0: NieuweVerhuur): Promise<RentalId> {
        if (this.processError) {
            try {
                const result = await this.actor.startVerhuur(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startVerhuur(arg0);
            return result;
        }
    }
    async verwijderProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verwijderProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verwijderProduct(arg0);
            return result;
        }
    }
    async voegProductToe(arg0: string, arg1: ProductType, arg2: string, arg3: bigint): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.voegProductToe(arg0, to_candid_ProductType_n25(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voegProductToe(arg0, to_candid_ProductType_n25(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async zoekProductOpQrCode(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.zoekProductOpQrCode(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.zoekProductOpQrCode(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProductType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ReserveringStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReserveringStatus): ReserveringStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Reservering_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservering): Reservering {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VerhuurStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerhuurStatus): VerhuurStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Verhuur_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Verhuur): Verhuur {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Verhuur]): Verhuur | null {
    return value.length === 0 ? null : from_candid_Verhuur_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReservationId;
    status: _ReserveringStatus;
    contactNaam: string;
    productIds: Array<_ProductId>;
    contactTelefoon: string;
    aangemaakt: _Timestamp;
    contactEmail: string;
    eindDatum: _Timestamp;
    startDatum: _Timestamp;
}): {
    id: ReservationId;
    status: ReserveringStatus;
    contactNaam: string;
    productIds: Array<ProductId>;
    contactTelefoon: string;
    aangemaakt: Timestamp;
    contactEmail: string;
    eindDatum: Timestamp;
    startDatum: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ReserveringStatus_n14(_uploadFile, _downloadFile, value.status),
        contactNaam: value.contactNaam,
        productIds: value.productIds,
        contactTelefoon: value.contactTelefoon,
        aangemaakt: value.aangemaakt,
        contactEmail: value.contactEmail,
        eindDatum: value.eindDatum,
        startDatum: value.startDatum
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    contactInfo: string;
    naam: string;
    role: _UserRole;
}): {
    principal: Principal;
    contactInfo: string;
    naam: string;
    role: UserRole;
} {
    return {
        principal: value.principal,
        contactInfo: value.contactInfo,
        naam: value.naam,
        role: from_candid_UserRole_n19(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RentalId;
    status: _VerhuurStatus;
    klantNaam: string;
    klantContact: string;
    productIds: Array<_ProductId>;
    isSet: boolean;
    eindDatum: _Timestamp;
    startDatum: _Timestamp;
}): {
    id: RentalId;
    status: VerhuurStatus;
    klantNaam: string;
    klantContact: string;
    productIds: Array<ProductId>;
    isSet: boolean;
    eindDatum: Timestamp;
    startDatum: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_VerhuurStatus_n4(_uploadFile, _downloadFile, value.status),
        klantNaam: value.klantNaam,
        klantContact: value.klantContact,
        productIds: value.productIds,
        isSet: value.isSet,
        eindDatum: value.eindDatum,
        startDatum: value.startDatum
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    maat: string;
    naam: string;
    prijsPerDag: bigint;
    productType: _ProductType;
    beschikbaar: boolean;
    qrCode: string;
}): {
    id: ProductId;
    maat: string;
    naam: string;
    prijsPerDag: bigint;
    productType: ProductType;
    beschikbaar: boolean;
    qrCode: string;
} {
    return {
        id: value.id,
        maat: value.maat,
        naam: value.naam,
        prijsPerDag: value.prijsPerDag,
        productType: from_candid_ProductType_n9(_uploadFile, _downloadFile, value.productType),
        beschikbaar: value.beschikbaar,
        qrCode: value.qrCode
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Boots: null;
} | {
    Snowboard: null;
} | {
    Bindingen: null;
}): ProductType {
    return "Boots" in value ? ProductType.Boots : "Snowboard" in value ? ProductType.Snowboard : "Bindingen" in value ? ProductType.Bindingen : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Bevestigd: null;
} | {
    InAfwachting: null;
} | {
    Geannuleerd: null;
}): ReserveringStatus {
    return "Bevestigd" in value ? ReserveringStatus.Bevestigd : "InAfwachting" in value ? ReserveringStatus.InAfwachting : "Geannuleerd" in value ? ReserveringStatus.Geannuleerd : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Admin: null;
} | {
    Medewerker: null;
}): UserRole {
    return "Admin" in value ? UserRole.Admin : "Medewerker" in value ? UserRole.Medewerker : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Actief: null;
} | {
    Ingeleverd: null;
} | {
    TeLaat: null;
}): VerhuurStatus {
    return "Actief" in value ? VerhuurStatus.Actief : "Ingeleverd" in value ? VerhuurStatus.Ingeleverd : "TeLaat" in value ? VerhuurStatus.TeLaat : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Verhuur>): Array<Verhuur> {
    return value.map((x)=>from_candid_Verhuur_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservering>): Array<Reservering> {
    return value.map((x)=>from_candid_Reservering_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ProductFilter_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maat?: string;
    productType?: ProductType;
    beschikbaar?: boolean;
}): {
    maat: [] | [string];
    productType: [] | [_ProductType];
    beschikbaar: [] | [boolean];
} {
    return {
        maat: value.maat ? candid_some(value.maat) : candid_none(),
        productType: value.productType ? candid_some(to_candid_ProductType_n25(_uploadFile, _downloadFile, value.productType)) : candid_none(),
        beschikbaar: value.beschikbaar ? candid_some(value.beschikbaar) : candid_none()
    };
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    Boots: null;
} | {
    Snowboard: null;
} | {
    Bindingen: null;
} {
    return value == ProductType.Boots ? {
        Boots: null
    } : value == ProductType.Snowboard ? {
        Snowboard: null
    } : value == ProductType.Bindingen ? {
        Bindingen: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
